name: CI/CD for Dynamics 365 Plugin

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '4.7.2'

      - name: Restore NuGet Packages
        run: nuget restore Dynamics365.Plugins.sln

      - name: Build Solution
        run: msbuild Dynamics365.Plugins.sln /p:Configuration=Release

      - name: Run Tests
        run: dotnet test --logger trx

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: plugin-dll
          path: bin/Release/*.dll

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: plugin-dll
          path: bin/Release/

      - name: Deploy to Dynamics 365
        run: |
          PowerPlatformImportSolution `
            -Url "https://your.crm.dynamics.com" `
            -ApplicationId "${{ secrets.APP_ID }}" `
            -ClientSecret "${{ secrets.CLIENT_SECRET }}" `
            -TenantId "${{ secrets.TENANT_ID }}" `
            -SolutionFile "bin/Release/Dynamics365.Plugins.dll"
